
p1=fmincon(@pDist, [1; 9; 1],...
	-eye(3), zeros(3,1), ...
	[],[],...  % A, b : linear equality
	[], [],...  % bounds...
	@nonLinPolytopeConstraints11, 'sqp' ... %function equality nonlinear
)

p2=fmincon(@pDist, [1; 9; 1],...
	-eye(3), zeros(3,1), ...
	[],[],...  % A, b : linear equality
	[], [],...  % bounds...
	@nonLinPolytopeConstraints11, 'sqp' ... %function equality nonlinear
)
